version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.0
      nodejs: 12
  build:
    commands:
      - composer install
      - npm install
      - npm run prod
      - rm -rf node_modules
      - vendor/bin/phpunit
artifacts:
  files:
    - "**/*"
