version: 2.1
jobs:
  build:
    machine: true
    docker:
      - image: circleci/php:8.0-fpm
    steps:
      - checkout
      - run:
          name: Setup docker
          command: |
            docker-compose build
            docker-compose up -d
            composer install -n --prefer-dist
      - run:
          name: Setup Laravel
          command: |
            cp .env.testing .env
            docker-compose run phpmyadmin php artisan key:generate
            docker-compose run phpmyadmin php artisan migrate:refresh --seed
      - run:
          name: Run Test
          command: |
            docker-compose run phpmyadmin vendor/bin/phpunit
