version: 2.1

jobs:
  build:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            sudo apt-get update
            sudo apt-get install -y docker-compose
      - run:
          name: Build and Run Docker Compose
          command: |
            docker-compose exec php bash -c "
              composer install
              cp .env.testing .env
              php artisan key:generate
              php artisan migrate:refresh --seed
              vendor/bin/phpunit
            "
