version: 2.1

jobs:
  build:
    docker:
      - image: circleci/php:7.4-node-browsers
      - image: circleci/mysql:8.0
      - image: circleci/nginx:1.21.1

    steps:
      - checkout

      - run:
          name: Install Docker Compose
          command: |
            sudo apt-get update
            sudo apt-get install -y docker-compose

      - run:
          name: Start Services
          command: docker-compose up -d

      - run:
          name: Wait for Services
          command: docker-compose exec php sh -c "while ! nc -z mysql 3306; do sleep 1; done"

      - run:
          name: Run Tests
          command: |
            docker-compose exec php sh -c "
              composer install
              php artisan key:generate
              php artisan migrate --seed
              php artisan test
            "

      - run:
          name: Stop Services
          command: docker-compose down
