version: 2.1

jobs:
  build:
    docker:
      - image: circleci/php:7.4-node-browsers
        environment:
          MYSQL_HOST: "db"
          MYSQL_PASSWORD: "root"
          MYSQL_PORT: 3306
      - image: circleci/mysql:8.0l
        environment:
          MYSQL_ROOT_PASSWORD: "root"
          MYSQL_DATABASE: "demo_test"
          MYSQL_USER: "root"
          MYSQL_PASSWORD: "root"
          MYSQL_HOST: "db"
        name: "db"
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            sudo apt-get update
            sudo apt-get install -y docker-compose
      - run:
          name: Build and Run Docker Compose
          command: |
            docker-compose up -d
            docker-compose exec php bash -c "
              composer install
              cp .env.testing .env
              php artisan key:generate
              php artisan migrate:refresh --seed
              vendor/bin/phpunit
            "
