version: 2.1

jobs:
  build:
    docker:
      - image: cimg/php:8.1.28-browsers
      - image: cimg/mysql:8.0
      - image: nginx:latest
    environment:
      - DB_CONNECTION: mysql_test
    steps:
      - checkout
      - run:
          name: Check composer.json existence
          command: |
            if [ -f "$HOME/project/composer.json" ]; then
              echo "composer.json exists in $HOME/project"
            else
              echo "composer.json does not exist in $HOME/project"
            fi
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install Docker Compose
          command: |
            sudo apt-get update
            sudo apt-get install -y docker-compose
            sed -i 's|./docker/nginx/default.conf|/docker/nginx|g' docker-compose.yml
            sed -i 's|/etc/nginx/conf.d/default.conf|/etc/nginx/conf.d|g' docker-compose.yml
            sed -i 's|./src:/var/www/|./src:$HOME/project|g' docker-compose.yml
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 3m
      - run:
          name: Start Nginx Container
          command: |
            docker run -d --name nginx_container -v /docker/nginx:/etc/nginx/conf.d -p 8081:80 nginx:latest
      - run:
          name: Build and Run Docker Compose
          working_directory: $HOME/project
          command: |
            docker-compose up -d
            docker-compose exec php bash -c "
              composer install
              cp .env.testing .env
              php artisan key:generate
              php artisan migrate:refresh --seed
              php artisan test
            "
