version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:8.0-node-browsers
    steps:
      - checkout
      - run:
          name: Setup docker
          command: |
            docker-compose build
            docker-compose up -d
            sudo composer self-update --1
            docker-compose run composer install -n --prefer-dist
      - run:
          name: Setup Laravel
          command: |
            cp .env.testing .env
            docker-compose run php artisan key:generate
            docker-compose run php artisan migrate:refresh --seed
      - run:
          name: Run Test
          command: |
            docker-compose run vendor/bin/phpunit
