version: 2
jobs:
  build:
    docker:
      - image: alpine
    steps:
      - checkout
      - run:
          name: Echo Test
          command: echo "CircleCI Test"
  deploy:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - SHA256:hAKPk6Ndeq4CzmrNAdS/Uti1XLB5K14rvu7motew+R8
      - run: ssh ${USER_NAME}@${HOST_NAME} 'cd /var/www/fleamarket && git pull'

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
