version: 2.1

jobs:
  build:
    docker:
      - image: circleci/php:8.0-fpm-browsers
    working_directory: /var/www
    steps:
      - checkout
      - run:
          name: Build Docker images
          command: docker-compose build
      - run:
          name: Start services
          command: docker-compose up -d
      - run:
          name: Run PHPUnit tests
          command: docker-compose exec php vendor/bin/phpunit

workflows:
  version: 2
  build:
    jobs:
      - build
