jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Setup docker
          command: |
            docker-compose build
            docker-compose up -d
            docker-compose run phpmyadmin composer install
      - run:
          name: Setup Laravel
          command: |
            cp .env.testing .env
            docker-compose run phpmyadmin php artisan key:generate
            docker-compose run phpmyadmin php artisan migrate:refresh --seed
      - run:
          name: Run Test
          command: |
            docker-compose run phpmyadmin vendor/bin/phpunit
