version: 2.1

jobs:
  build:
    docker:
      - image: cimg/php:8.1.28-browsers
      - image: cimg/mysql:8.0
      - image: nginx:latest
    environment:
      - DB_CONNECTION: mysql_test
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install Docker Compose
          command: |
            sudo apt-get update
            sudo apt-get install -y docker-compose
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 3m
      - run:
          name: Start MySQL Container
          command: |
            docker run -d --name mysql_container -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=demo_test -p 3306:3306 cimg/mysql:8.0
      - run:
          name: Start PHP Container
          command: |
            docker run -d --name php_container -v /path/to/local/code:/app -w /app cimg/php:8.1.28-browsers php -S 0.0.0.0:8000
      - run:
          name: Start Nginx Container
          command: |
            docker run -d --name nginx_container -v /path/to/nginx/conf:/etc/nginx/conf.d -p 8080:80 nginx:latest
      - run:
          name: Build and Run Docker Compose
          command: |
            docker-compose up -d
            docker-compose exec php bash -c "
              composer install
              cp .env.testing .env
              php artisan key:generate
              php artisan migrate:refresh --seed
              vendor/bin/phpunit
            "
