version: 2.1

jobs:
  build:
    docker:
      - image: circleci/php:7.4-node-browsers
      - image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD: root
      - MYSQL_DATABASE: demo_test
      - MYSQL_USER: root
      - MYSQL_PASSWORD: root
    steps:
      - checkout
      - run:
          name: Install MySQL Client
          command: |
            sudo apt-get update
            sudo apt-get install -y mysql-client
      - run:
          name: Remove Google Chrome apt repository
          command: sudo rm -f /etc/apt/sources.list.d/google-chrome.list*
      - run:
          name: Install Docker Compose
          command: |
            sudo apt-get update
            sudo apt-get install -y docker-compose
      - run:
          name: Build and Run Docker Compose
          command: |
            docker-compose up -d
            docker-compose exec php bash -c "
              composer install
              cp .env.testing .env
              php artisan key:generate
              php artisan migrate:refresh --seed
              vendor/bin/phpunit
            "
