version: 2.1

jobs:
  build:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            sudo apt-get update
            sudo apt-get install -y docker-compose
      - run:
          name: Build and Run Docker Compose
          command: |
            docker-compose up -d
            docker-compose run composer install
            docker-compose run php cp .env.testing .env
            docker-compose run php php artisan key:generate
            docker-compose run php php artisan migrate:refresh --seed
            docker-compose run php vendor/bin/phpunit
